package com.payroll.bot.telegram;

public enum BotState {
    AWAITING_PASSWORD,
    ONBOARDING_HOURLY_RATE,
    ONBOARDING_MONTHLY_TAX,
    MAIN_MENU,
    ADD_INCOME_DATE,
    ADD_INCOME_CUSTOM_DATE,
    ADD_INCOME_SERVICE,
    ADD_INCOME_VALUE,
    EDIT_HOURLY_RATE,
    EDIT_TAX,
    EDIT_TRANSACTION_VALUE,
    ADD_BUDGET_CATEGORY_NAME,
    ADD_BUDGET_CATEGORY_LIMIT,
    BUDGET_MENU,
    ONBOARDING_ADD_SERVICE_NAME,
    ONBOARDING_ADD_SERVICE_PERCENTAGE,
    SETTINGS_MANAGE_SERVICES,
    SETTINGS_ADD_SERVICE_NAME,
    SETTINGS_ADD_SERVICE_PERCENTAGE,
    SETTINGS_RENAME_SERVICE_NAME,
    SETTINGS_UPDATE_SERVICE_PERCENTAGE,
    
    // Basic limits setup and editing
    BUDGET_SETUP_RENT,
    BUDGET_SETUP_FOOD,
    BUDGET_SETUP_ADDITIONAL,
    EDIT_BUDGET_RENT,
    EDIT_BUDGET_FOOD,
    EDIT_BUDGET_ADDITIONAL
}
